### ISSUE TITLE
自动构建

### ISSUE THREAD

**Issue by cathaysia** [rRemix/APlayer#121]
能否打开自动构建？
我看到代码昨天就更新了，但是 release 明显发布要晚一点，如果使用 actions 构建的话也许会方便很多。
我本来是想提个相关的 PR 的，可是在 ./app/build.gradle 第55行报错了，百度上似乎要求将 signingConfigs 的配置去掉。我猜它应该是用来签名的，可是我对安卓实在是不了解，就不打算改代码了。

actions 里面已经提供了 gradle 构建的模板。完成构建后可以使用 `marvinpinto/action-automatic-releases@latest` 这个 action把它上传到 release. 它的用法如下：

```yml
            - name: Release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: ${{ github.run_id }}
                  prerelease: false
                  title: ${{ github.run_id }}
                  files: |
                      ./html.rar
                      ./_build/latex/*.pdf
```

仓库 https://github.com/cathaysia/youtube-download-and-release 和 https://github.com/cathaysia/aria2-download-and-release 都用到了这个 action。
